version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-express-app:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
